name: Docker Build and Push
permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/casb02/podotherapy_backend/podiatryapp:latest

  deploy:
    runs-on: ubuntu-latest
    environment: Prod
    needs: docker

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure
        uses: appleboy/ssh-action@v0.1.6
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: azureuser
          key: ${{ secrets.KEY }}
          envs: TOKEN
          script: |
            docker login ghcr.io -u Casb02 -p $TOKEN
            docker pull ghcr.io/casb02/podotherapy_backend/podiatryapp:latest
            docker-compose down
            docker-compose up -d